name: Github Pages Deploy

on:
    push:
        branches:
            - 'master'

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Checkout (Sprawdzenie)
              uses: actions/checkout@v2

            - name: Install and build (Instalacja i budowa)
              run: npm install && npm run build

            - run: touch ./out/.nojekyll

            - name: Deploy 🚀 (Deplojojowanie strony :D
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  branch: gh-pages
                  folder: out
